import mongoose from "mongoose";

const bbaFormSchema = new mongoose.Schema({
    course: { type: String, default: "BBA" },
    surname: { type: String },
    firstName: { type: String },
    fathersName: { type: String },
    mothersName: { type: String },
    caste: { type: String },
    category: { type: String },
    yearAdmitted: { type: String },
    specialization: { type: String },
    religion: { type: String },
    fromMaharashtra: { type: String },
    academicYear: { type: String },
    universityEnrlNumber: { type: String },
    dob: { type: String },
    gender: { type: String },
    isHandicapped: { type: String },
    disability: { type: String},
    relation: { type: String },
    localGuardianName: { type: String },
    localGuardianRelation: { type: String },
    localGuardianMobile1: { type: String },
    localGuardianMobile2: { type: String },
    localGuardianAddress: { type: String },
    permanentAddress: { type: String },
    district: { type: String },
    state: { type: String },
    pinCode:   { type: String },
    fathersMobileNo1: { type: String },
    fathersMobileNo2: { type: String },
    mothersMobileNo1: { type: String },
    mothersMobileNo2: { type: String },
    studentsMobileNo1: { type: String },
    studentsMobileNo2: { type: String },
    studentsWhatsappNo1: { type: String },
    studentsWhatsappNo2: { type: String },
    studentsEmail: { type: String },
    fathersWhatsappNo2: { type: String },
    fathersOccupation: { type: String },
    designation: { type: String },
    graduationPercentage: { type: String },
    graduationYear: { type: String },
    otherYear: { type: String },    
    division: { type: String },
    collegeName: { type: String },

    sscStreamName: { type: String},
    sscSchoolName: { type: String},
    sscBoard: { type: String},
    sscTotalMarks: { type: Number},
    sscOutOf: { type: Number},
    sscPercentage: { type: Number},
    sscGrade: { type: String},
    sscYearOfPassing: { type: String},

    hscStreamName: { type: String},
    hscSchoolName: { type: String},
    hscBoard: { type: String},
    hscTotalMarks: { type: Number},
    hscOutOf: { type: Number},
    hscPercentage: { type: Number},
    hscGrade: { type: String},
    hscYearOfPassing: { type: String},

    otherStreamName: { type: String},
    otherSchoolName: { type: String},
    otherBoard: { type: String},
    otherTotalMarks: { type: Number},
    otherOutOf: { type: Number},
    otherPercentage: { type: Number},
    otherGrade: { type: String},
    otherYearOfPassing: { type: String},
    deleted: { type: Boolean, default: false },
}, { timestamps: true });

const BbaFormModel = mongoose.model("bbaForm", bbaFormSchema);

export default BbaFormModel;